#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

otb_set_interface() {
	[ "$(uci -q get "network.$1")" = interface ] && return
	uci -q batch <<-EOF
	set network.$1=interface
	set network.$1.ifname='$2'
	set network.$1.proto='$3'
	EOF
}

otb_set_macvlan() {
	[ "$(uci -q get "network.$1_dev")" = device ] && return
	ifname=$(uci -q get "network.$1.ifname")
	uci -q batch <<-EOF
	set network.$1_dev=device
	set network.$1_dev.name='$1'
	set network.$1_dev.type='macvlan'
	set network.$1_dev.ifname='$ifname'
	set network.$1_dev.macaddr='auto'
	set network.$1.ifname='$1'
	EOF
}

board="$(cat /tmp/sysinfo/board_name)" 2>/dev/null

case "$board" in
*overthebox-v2b)
	# TODO
	#ucidef_add_switch "otbv2sw" "15t@eth0" "16:none" \
	#	"1:lan" "2:lan" "3:lan" "4:lan" "5:lan" "6:lan" \
	#	"7:lan" "8:lan" "9:lan" "10:lan" "11:lan" "12:lan" \
	#	"17:lan" "18:lan" "13:wan13" "14:wan14"
	return 0;
	;;
esac

otb_set_interface lan eth0 static

num=0

for i in /sys/class/net/eth*; do
	case "$i" in
	/sys/class/net/eth0)
		;;
	/sys/class/net/eth*)
		num=${i##*/eth}
		otb_set_interface "wan$num" "eth$num" dhcp
		;;
	esac
done

if [ "$num" = 0 ]; then
	otb_set_macvlan lan
	otb_set_interface wan eth0 dhcp
	otb_set_macvlan wan
fi
